// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolClient.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CW {

  /// <summary>Holder for reflection information generated from ProtocolClient.proto</summary>
  public static partial class ProtocolClientReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtocolClient.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolClientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b2NvbENsaWVudC5wcm90bxICQ1caDlByb3RvY29sLnByb3RvIk0K",
            "FENTX1BhY2tldExvZ2luS2V5UmVxEhkKA2lkMRgBIAEoDjIMLkNXLlBhY2tl",
            "dElEEhoKA2lkMhgCIAEoDjINLkNXLlBhY2tldElEMiJaChRDU19QYWNrZXRM",
            "b2dpbktleVJlcxIZCgNpZDEYASABKA4yDC5DVy5QYWNrZXRJRBIaCgNpZDIY",
            "AiABKA4yDS5DVy5QYWNrZXRJRDISCwoDa2V5GAMgAygFIowBChZDU19QYWNr",
            "ZXRMb2dpbkxvZ2luUmVxEhkKA2lkMRgBIAEoDjIMLkNXLlBhY2tldElEEhoK",
            "A2lkMhgCIAEoDjINLkNXLlBhY2tldElEMhIQCgh1c2VybmFtZRgDIAEoCRIO",
            "CgZwYXNzd2QYBCABKAkSCwoDdmVyGAUgASgJEgwKBGpzb24YBiABKAkihwIK",
            "FkNTX1BhY2tldExvZ2luTG9naW5SZXMSGQoDaWQxGAEgASgOMgwuQ1cuUGFj",
            "a2V0SUQSGgoDaWQyGAIgASgOMg0uQ1cuUGFja2V0SUQyEh8KA3JlcxgDIAEo",
            "DjISLkNXLnJldF9lcnJvcl9jb2RlEhAKCGxhc3Rnc2lkGAQgASgFEhIKCmxh",
            "c3Rnc25hbWUYBSABKAkSDgoGZ3NsaXN0GAYgAygFEg4KBnJlYXNvbhgHIAEo",
            "CRIMCgR0aW1lGAggASgNEgwKBGpzb24YCSABKAkSEQoJcmVtYWluc2VjGAog",
            "ASgFEhAKCHVzZXJuYW1lGAsgASgJEg4KBm9udGltZRgMIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CW.ProtocolReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CW.CS_PacketLoginKeyReq), global::CW.CS_PacketLoginKeyReq.Parser, new[]{ "Id1", "Id2" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CW.CS_PacketLoginKeyRes), global::CW.CS_PacketLoginKeyRes.Parser, new[]{ "Id1", "Id2", "Key" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CW.CS_PacketLoginLoginReq), global::CW.CS_PacketLoginLoginReq.Parser, new[]{ "Id1", "Id2", "Username", "Passwd", "Ver", "Json" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CW.CS_PacketLoginLoginRes), global::CW.CS_PacketLoginLoginRes.Parser, new[]{ "Id1", "Id2", "Res", "Lastgsid", "Lastgsname", "Gslist", "Reason", "Time", "Json", "Remainsec", "Username", "Ontime" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CS_PacketLoginKeyReq : pb::IMessage<CS_PacketLoginKeyReq> {
    private static readonly pb::MessageParser<CS_PacketLoginKeyReq> _parser = new pb::MessageParser<CS_PacketLoginKeyReq>(() => new CS_PacketLoginKeyReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CS_PacketLoginKeyReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CW.ProtocolClientReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginKeyReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginKeyReq(CS_PacketLoginKeyReq other) : this() {
      id1_ = other.id1_;
      id2_ = other.id2_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginKeyReq Clone() {
      return new CS_PacketLoginKeyReq(this);
    }

    /// <summary>Field number for the "id1" field.</summary>
    public const int Id1FieldNumber = 1;
    private global::CW.PacketID id1_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID Id1 {
      get { return id1_; }
      set {
        id1_ = value;
      }
    }

    /// <summary>Field number for the "id2" field.</summary>
    public const int Id2FieldNumber = 2;
    private global::CW.PacketID2 id2_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID2 Id2 {
      get { return id2_; }
      set {
        id2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CS_PacketLoginKeyReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CS_PacketLoginKeyReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id1 != other.Id1) return false;
      if (Id2 != other.Id2) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id1 != 0) hash ^= Id1.GetHashCode();
      if (Id2 != 0) hash ^= Id2.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id1 != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id1);
      }
      if (Id2 != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Id2);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id1);
      }
      if (Id2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id2);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CS_PacketLoginKeyReq other) {
      if (other == null) {
        return;
      }
      if (other.Id1 != 0) {
        Id1 = other.Id1;
      }
      if (other.Id2 != 0) {
        Id2 = other.Id2;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            id1_ = (global::CW.PacketID) input.ReadEnum();
            break;
          }
          case 16: {
            id2_ = (global::CW.PacketID2) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CS_PacketLoginKeyRes : pb::IMessage<CS_PacketLoginKeyRes> {
    private static readonly pb::MessageParser<CS_PacketLoginKeyRes> _parser = new pb::MessageParser<CS_PacketLoginKeyRes>(() => new CS_PacketLoginKeyRes());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CS_PacketLoginKeyRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CW.ProtocolClientReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginKeyRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginKeyRes(CS_PacketLoginKeyRes other) : this() {
      id1_ = other.id1_;
      id2_ = other.id2_;
      key_ = other.key_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginKeyRes Clone() {
      return new CS_PacketLoginKeyRes(this);
    }

    /// <summary>Field number for the "id1" field.</summary>
    public const int Id1FieldNumber = 1;
    private global::CW.PacketID id1_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID Id1 {
      get { return id1_; }
      set {
        id1_ = value;
      }
    }

    /// <summary>Field number for the "id2" field.</summary>
    public const int Id2FieldNumber = 2;
    private global::CW.PacketID2 id2_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID2 Id2 {
      get { return id2_; }
      set {
        id2_ = value;
      }
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_key_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> key_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Key {
      get { return key_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CS_PacketLoginKeyRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CS_PacketLoginKeyRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id1 != other.Id1) return false;
      if (Id2 != other.Id2) return false;
      if(!key_.Equals(other.key_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id1 != 0) hash ^= Id1.GetHashCode();
      if (Id2 != 0) hash ^= Id2.GetHashCode();
      hash ^= key_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id1 != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id1);
      }
      if (Id2 != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Id2);
      }
      key_.WriteTo(output, _repeated_key_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id1);
      }
      if (Id2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id2);
      }
      size += key_.CalculateSize(_repeated_key_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CS_PacketLoginKeyRes other) {
      if (other == null) {
        return;
      }
      if (other.Id1 != 0) {
        Id1 = other.Id1;
      }
      if (other.Id2 != 0) {
        Id2 = other.Id2;
      }
      key_.Add(other.key_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            id1_ = (global::CW.PacketID) input.ReadEnum();
            break;
          }
          case 16: {
            id2_ = (global::CW.PacketID2) input.ReadEnum();
            break;
          }
          case 26:
          case 24: {
            key_.AddEntriesFrom(input, _repeated_key_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CS_PacketLoginLoginReq : pb::IMessage<CS_PacketLoginLoginReq> {
    private static readonly pb::MessageParser<CS_PacketLoginLoginReq> _parser = new pb::MessageParser<CS_PacketLoginLoginReq>(() => new CS_PacketLoginLoginReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CS_PacketLoginLoginReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CW.ProtocolClientReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginLoginReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginLoginReq(CS_PacketLoginLoginReq other) : this() {
      id1_ = other.id1_;
      id2_ = other.id2_;
      username_ = other.username_;
      passwd_ = other.passwd_;
      ver_ = other.ver_;
      json_ = other.json_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginLoginReq Clone() {
      return new CS_PacketLoginLoginReq(this);
    }

    /// <summary>Field number for the "id1" field.</summary>
    public const int Id1FieldNumber = 1;
    private global::CW.PacketID id1_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID Id1 {
      get { return id1_; }
      set {
        id1_ = value;
      }
    }

    /// <summary>Field number for the "id2" field.</summary>
    public const int Id2FieldNumber = 2;
    private global::CW.PacketID2 id2_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID2 Id2 {
      get { return id2_; }
      set {
        id2_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 3;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "passwd" field.</summary>
    public const int PasswdFieldNumber = 4;
    private string passwd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Passwd {
      get { return passwd_; }
      set {
        passwd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ver" field.</summary>
    public const int VerFieldNumber = 5;
    private string ver_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ver {
      get { return ver_; }
      set {
        ver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "json" field.</summary>
    public const int JsonFieldNumber = 6;
    private string json_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Json {
      get { return json_; }
      set {
        json_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CS_PacketLoginLoginReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CS_PacketLoginLoginReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id1 != other.Id1) return false;
      if (Id2 != other.Id2) return false;
      if (Username != other.Username) return false;
      if (Passwd != other.Passwd) return false;
      if (Ver != other.Ver) return false;
      if (Json != other.Json) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id1 != 0) hash ^= Id1.GetHashCode();
      if (Id2 != 0) hash ^= Id2.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Passwd.Length != 0) hash ^= Passwd.GetHashCode();
      if (Ver.Length != 0) hash ^= Ver.GetHashCode();
      if (Json.Length != 0) hash ^= Json.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id1 != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id1);
      }
      if (Id2 != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Id2);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (Passwd.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Passwd);
      }
      if (Ver.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Ver);
      }
      if (Json.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Json);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id1);
      }
      if (Id2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id2);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Passwd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Passwd);
      }
      if (Ver.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ver);
      }
      if (Json.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Json);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CS_PacketLoginLoginReq other) {
      if (other == null) {
        return;
      }
      if (other.Id1 != 0) {
        Id1 = other.Id1;
      }
      if (other.Id2 != 0) {
        Id2 = other.Id2;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Passwd.Length != 0) {
        Passwd = other.Passwd;
      }
      if (other.Ver.Length != 0) {
        Ver = other.Ver;
      }
      if (other.Json.Length != 0) {
        Json = other.Json;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            id1_ = (global::CW.PacketID) input.ReadEnum();
            break;
          }
          case 16: {
            id2_ = (global::CW.PacketID2) input.ReadEnum();
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Passwd = input.ReadString();
            break;
          }
          case 42: {
            Ver = input.ReadString();
            break;
          }
          case 50: {
            Json = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CS_PacketLoginLoginRes : pb::IMessage<CS_PacketLoginLoginRes> {
    private static readonly pb::MessageParser<CS_PacketLoginLoginRes> _parser = new pb::MessageParser<CS_PacketLoginLoginRes>(() => new CS_PacketLoginLoginRes());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CS_PacketLoginLoginRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CW.ProtocolClientReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginLoginRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginLoginRes(CS_PacketLoginLoginRes other) : this() {
      id1_ = other.id1_;
      id2_ = other.id2_;
      res_ = other.res_;
      lastgsid_ = other.lastgsid_;
      lastgsname_ = other.lastgsname_;
      gslist_ = other.gslist_.Clone();
      reason_ = other.reason_;
      time_ = other.time_;
      json_ = other.json_;
      remainsec_ = other.remainsec_;
      username_ = other.username_;
      ontime_ = other.ontime_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CS_PacketLoginLoginRes Clone() {
      return new CS_PacketLoginLoginRes(this);
    }

    /// <summary>Field number for the "id1" field.</summary>
    public const int Id1FieldNumber = 1;
    private global::CW.PacketID id1_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID Id1 {
      get { return id1_; }
      set {
        id1_ = value;
      }
    }

    /// <summary>Field number for the "id2" field.</summary>
    public const int Id2FieldNumber = 2;
    private global::CW.PacketID2 id2_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.PacketID2 Id2 {
      get { return id2_; }
      set {
        id2_ = value;
      }
    }

    /// <summary>Field number for the "res" field.</summary>
    public const int ResFieldNumber = 3;
    private global::CW.ret_error_code res_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CW.ret_error_code Res {
      get { return res_; }
      set {
        res_ = value;
      }
    }

    /// <summary>Field number for the "lastgsid" field.</summary>
    public const int LastgsidFieldNumber = 4;
    private int lastgsid_;
    /// <summary>
    /// 最近登录过的gsid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Lastgsid {
      get { return lastgsid_; }
      set {
        lastgsid_ = value;
      }
    }

    /// <summary>Field number for the "lastgsname" field.</summary>
    public const int LastgsnameFieldNumber = 5;
    private string lastgsname_ = "";
    /// <summary>
    /// 最近登录过的gs name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Lastgsname {
      get { return lastgsname_; }
      set {
        lastgsname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gslist" field.</summary>
    public const int GslistFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_gslist_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> gslist_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 我有登录过的gsid列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Gslist {
      get { return gslist_; }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 7;
    private string reason_ = "";
    /// <summary>
    /// 封你的理由
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Reason {
      get { return reason_; }
      set {
        reason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 8;
    private uint time_;
    /// <summary>
    /// 当前时间，1970到现在秒数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "json" field.</summary>
    public const int JsonFieldNumber = 9;
    private string json_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Json {
      get { return json_; }
      set {
        json_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "remainsec" field.</summary>
    public const int RemainsecFieldNumber = 10;
    private int remainsec_;
    /// <summary>
    /// 封停账号的话，这是封停剩余秒数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Remainsec {
      get { return remainsec_; }
      set {
        remainsec_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 11;
    private string username_ = "";
    /// <summary>
    /// sdk账号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ontime" field.</summary>
    public const int OntimeFieldNumber = 12;
    private int ontime_;
    /// <summary>
    /// 累积在线时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Ontime {
      get { return ontime_; }
      set {
        ontime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CS_PacketLoginLoginRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CS_PacketLoginLoginRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id1 != other.Id1) return false;
      if (Id2 != other.Id2) return false;
      if (Res != other.Res) return false;
      if (Lastgsid != other.Lastgsid) return false;
      if (Lastgsname != other.Lastgsname) return false;
      if(!gslist_.Equals(other.gslist_)) return false;
      if (Reason != other.Reason) return false;
      if (Time != other.Time) return false;
      if (Json != other.Json) return false;
      if (Remainsec != other.Remainsec) return false;
      if (Username != other.Username) return false;
      if (Ontime != other.Ontime) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id1 != 0) hash ^= Id1.GetHashCode();
      if (Id2 != 0) hash ^= Id2.GetHashCode();
      if (Res != 0) hash ^= Res.GetHashCode();
      if (Lastgsid != 0) hash ^= Lastgsid.GetHashCode();
      if (Lastgsname.Length != 0) hash ^= Lastgsname.GetHashCode();
      hash ^= gslist_.GetHashCode();
      if (Reason.Length != 0) hash ^= Reason.GetHashCode();
      if (Time != 0) hash ^= Time.GetHashCode();
      if (Json.Length != 0) hash ^= Json.GetHashCode();
      if (Remainsec != 0) hash ^= Remainsec.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Ontime != 0) hash ^= Ontime.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id1 != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id1);
      }
      if (Id2 != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Id2);
      }
      if (Res != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Res);
      }
      if (Lastgsid != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Lastgsid);
      }
      if (Lastgsname.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Lastgsname);
      }
      gslist_.WriteTo(output, _repeated_gslist_codec);
      if (Reason.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Reason);
      }
      if (Time != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Time);
      }
      if (Json.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Json);
      }
      if (Remainsec != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Remainsec);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Username);
      }
      if (Ontime != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Ontime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id1);
      }
      if (Id2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id2);
      }
      if (Res != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Res);
      }
      if (Lastgsid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lastgsid);
      }
      if (Lastgsname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Lastgsname);
      }
      size += gslist_.CalculateSize(_repeated_gslist_codec);
      if (Reason.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reason);
      }
      if (Time != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
      }
      if (Json.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Json);
      }
      if (Remainsec != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Remainsec);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Ontime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Ontime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CS_PacketLoginLoginRes other) {
      if (other == null) {
        return;
      }
      if (other.Id1 != 0) {
        Id1 = other.Id1;
      }
      if (other.Id2 != 0) {
        Id2 = other.Id2;
      }
      if (other.Res != 0) {
        Res = other.Res;
      }
      if (other.Lastgsid != 0) {
        Lastgsid = other.Lastgsid;
      }
      if (other.Lastgsname.Length != 0) {
        Lastgsname = other.Lastgsname;
      }
      gslist_.Add(other.gslist_);
      if (other.Reason.Length != 0) {
        Reason = other.Reason;
      }
      if (other.Time != 0) {
        Time = other.Time;
      }
      if (other.Json.Length != 0) {
        Json = other.Json;
      }
      if (other.Remainsec != 0) {
        Remainsec = other.Remainsec;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Ontime != 0) {
        Ontime = other.Ontime;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            id1_ = (global::CW.PacketID) input.ReadEnum();
            break;
          }
          case 16: {
            id2_ = (global::CW.PacketID2) input.ReadEnum();
            break;
          }
          case 24: {
            res_ = (global::CW.ret_error_code) input.ReadEnum();
            break;
          }
          case 32: {
            Lastgsid = input.ReadInt32();
            break;
          }
          case 42: {
            Lastgsname = input.ReadString();
            break;
          }
          case 50:
          case 48: {
            gslist_.AddEntriesFrom(input, _repeated_gslist_codec);
            break;
          }
          case 58: {
            Reason = input.ReadString();
            break;
          }
          case 64: {
            Time = input.ReadUInt32();
            break;
          }
          case 74: {
            Json = input.ReadString();
            break;
          }
          case 80: {
            Remainsec = input.ReadInt32();
            break;
          }
          case 90: {
            Username = input.ReadString();
            break;
          }
          case 96: {
            Ontime = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
